### PR TITLE
Automatically fetch contributor info

### PR DESCRIPTION
**Pull request by Scott2bReal**
Issue #7 
This is my first ever pull request! I hope everything is in order. I had a little trouble organizing git stuff on my end, but I think I got it figured out.

### CODE REVIEW

**Comment by vnugent** [comment]
It looks great!!   Thank you.

A minor style related question, since some people don't capitalize their name and some do,  what do you think if we capitalize all names, either all caps or just the first letter?

https://tailwindcss.com/docs/text-transform#transforming-text

I'm wondering how that would look.  Can you please make a quick change and share a screen shot?

**Comment by Scott2bReal** [comment]
Here are some screenshots with the different options. I've included one showing the names without modification for completeness.

## As-is
image

## Capitalize
image

## Uppercase
image

Personally, I think the capitalize version looks the best. It provides contrast to the contributions which are uppercase, while providing uniformity which is not present in the as-is version. I'm so new to this though that I would defer to your (or anyone else's) opinion!

**Comment by vnugent** [comment]
Agreed.  The all caps version looks best. Thank you for your help!

Edit: sorry I clicked the merge button by accident.  Can you push the capitalize version?

**Comment by Scott2bReal** [comment]
Definitely! Just to be clear, you'd like the capitalize version ("Admanny") and not the all-caps version ("ADMANNY")?

**Comment by vnugent** [comment]
I meant the Capitalize version. Thanks!

**Comment by Scott2bReal** [comment]
Ok great! I've pushed the commit to the `update-contributors` branch of my fork. Do I need to submit a new PR?

**Comment by vnugent** [comment]
I created the PR on your behalf.  It's live now! thanks

**Comment by vnugent** [comment]
@all-contributors add @Scott2bReal for code

**Comment by Scott2bReal** [comment]
Amazing, glad I was able to contribute! Thanks for making that PR

**Pull request merged**
